
DROP VIEW IF EXISTS dept_emp_relations;
DROP TABLE IF EXISTS DEPT_EMP;
DROP TABLE IF EXISTS DEPT_MANAGER;
DROP TABLE IF EXISTS SALARIES;
DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS TITLES;


CREATE TABLE DEPARTMENTS(
    DEPT_NO VARCHAR PRIMARY KEY,
    DEPT_NAME VARCHAR NOT NULL
);

CREATE TABLE TITLES(
    TITLE_ID VARCHAR PRIMARY KEY,
    TITLE VARCHAR NOT NULL
);

CREATE TABLE EMPLOYEES(
    EMP_NO INT PRIMARY KEY,
    EMP_TITLE_ID VARCHAR REFERENCES TITLES(TITLE_ID),
    BIRTH_DATE DATE NOT NULL,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    SEX CHAR NOT NULL,
    HIRE_DATE DATE NOT NULL
);

CREATE TABLE SALARIES(
    EMP_NO INT REFERENCES EMPLOYEES(EMP_NO),
    SALARY INT NOT NULL
);

CREATE TABLE DEPT_EMP(
    EMP_NO INT REFERENCES EMPLOYEES(EMP_NO),
    DEPT_NO VARCHAR REFERENCES DEPARTMENTS(DEPT_NO),
    PRIMARY KEY(DEPT_NO , EMP_NO)
);

CREATE TABLE DEPT_MANAGER(
    DEPT_NO VARCHAR REFERENCES DEPARTMENTS(DEPT_NO),
    EMP_NO INT REFERENCES EMPLOYEES(EMP_NO),
    PRIMARY KEY(DEPT_NO , EMP_NO)
);